# Generated by Django 6.0.5 on 2026-06-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('mechanical', 'Mechanical Engineering'), ('welding', 'Welding'), ('fabrication', 'Fabrication'), ('repair', 'Repair & Maintenance')], max_length=50)),
                ('client_name', models.CharField(blank=True, help_text='Client name or company', max_length=100)),
                ('location', models.CharField(help_text='Where was the work done?', max_length=200)),
                ('problem', models.TextField(help_text='What was the problem?')),
                ('solution', models.TextField(help_text='How did we solve it?')),
                ('results', models.TextField(blank=True, help_text='What were the results?')),
                ('image', models.ImageField(blank=True, null=True, upload_to='case_studies/')),
                ('before_image', models.ImageField(blank=True, help_text='Before fix photo', null=True, upload_to='case_studies/before/')),
                ('after_image', models.ImageField(blank=True, help_text='After fix photo', null=True, upload_to='case_studies/after/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
