# Generated by Django 6.0.5 on 2026-06-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='location',
            field=models.CharField(default=3456, help_text='Where is the problem/site located?', max_length=200),
            preserve_default=False,
        ),
    ]
